### ISSUE TITLE
Field Validation Doen't Work On The Final Step

### ISSUE THREAD

**Issue by carterax** [betaWeb/zangdar#2]
Beautiful Project, thanks for making this saved me a lot of time.
I'm hoping you could you could look into why at the last step of the form the custom validation function doesn't work and instead native HTML validation works in it's place. I'm using the Formr validation library.

Thank you

**Comment by betaWeb** [comment]
@carterax thanks a lot :) 

I'm gonna investigate that asap. At the same time, can you put the code you have on your final step, and for the wizard please ?

**Comment by carterax** [comment]
Thanks for your response, a good example of the aforementioned issue is this codepen 
[https://codepen.io/betaweb/pen/dLBbbq](url)

On the last step if any of the input fields have required or any native html validation attribute, the custom validation setup doesn't work

**Comment by carterax** [comment]
@betaWeb i found a work around which involved overriding the forms submit event before initiating zangdar. Thanks so much for your help this will serve.

**Comment by betaWeb** [comment]
@carterax ok great 👌

Can you put here your workaround, it can helps other users too 🙂

Thanks you.

**Comment by carterax** [comment]
**Form override first**

```javascript
$(document).on('submit', $form_group, function(e){
    e.preventDefault()
    return false;
});
```
**Zangdar initiation afterwards**

```javascript
let wizard = new Zangdar($form_group, {
    submit_selector: '#form-submit-btn',
    onSubmit(e) {
         e.preventDefault();
    },
    customValidation(step, fields, form) {
        const validator = new Formr(form);

        validator.messages({
            'required': messages[0],
            'email': messages[1],
            'number': messages[2]
        })

        Object.keys(fields).map((field, idx) => {
            switch(fields[field].type) {
                case 'text':
                    if (fields[field].required) {
                        validator
                            .required(fields[field].id)
                            .string(fields[field].id)
                    }
                break;
                case 'email':
                    if (fields[field].required) {
                        validator
                            .email(fields[field].id)
                            .required(fields[field].id)
                    } else {
                        validator
                            .email(fields[field].id)
                    }
                break;
                case 'number':
                case 'tel':
                    if (fields[field].required) {
                        validator
                            .required(fields[field].id)
                            .number(fields[field].id)
                    } else {
                        validator
                            .number(fields[field].id)
                    }
                break;
                default:
                    if (fields[field].required) {
                        validator
                            .required(fields[field].id)
                    }
            }
        })

        if (!validator.isValid()) {
            handleErrors(validator.getErrors(), $form_group);
            let id = fields[Object.keys(fields)[0]].id;

            $('html, body').animate({
                scrollTop: $("#" + id).offset().top - 100
            }, 500);
            return false;
        }

        return true;
    }
)
```
This method stopped the form submitting despite errors being thrown by Formr, while this worked i found native HTML validation still forcing it's way through in Chrome.

**Comment by betaWeb** [comment]
@carterax thanks for sharing this workaround ;) 

i'll fix this behavior asap, because the custom validation must works even if it's the last step (step with submission).
